namespace Wilnaatahl.ECS

open System
#if FABLE_COMPILER
open Fable.Core
#endif

// Here we define types that act as bindings to Koota, an ECS library for TypeScript.
// There interfaces can also be mocked in .NET tests to exercise the F# implementation
// of all our systems.
//
// While in theory these interfaces could map to any TypeScript ECS, their design is
// heavily biased towards Koota's for ease of interop.
//
// NOTE: The heavy use of interfaces is to facilitate interop with TypeScript.
// The Fable compiler won't mangle interface member names, and as much as I'd love
// to use discriminated unions here, they're pretty ugly in TypeScript.

/// Represents a trait (a.k.a. component or aspect) of a specific type
/// that can be added to or removed from an entity.
type ITrait =
    /// Used to distinguish ITagTrait from IValueTrait in TypeScript type tests.
    /// We can't use a discriminated union for traits because it would force the
    /// type parameter of IValueTrait up to this interface.
    abstract IsTag: bool

/// Represents a trait (a.k.a. component or aspect) that can be added to
/// or removed from an entity and represents a "tag" or "flag" on that entity.
type ITagTrait =
    inherit ITrait

/// Represents a trait (a.k.a. component or aspect) that can be added to
/// or removed from an entity and carries values of a specific type.
type IValueTrait<'T> =
    inherit ITrait

/// Represents a query criteria consisting of traits or combinations thereof.
#if FABLE_COMPILER
[<TypeScriptTaggedUnion("type")>]
#endif
type QueryOperator =
    | With of ITrait
    | Not of QueryOperator[]
    | Or of QueryOperator[]

    // It's static to make the name generated by Fable more palatable on the TypeScript side.
    static member Visit fWith fNot fOr op =
        let rec visit innerOp =
            match innerOp with
            | With t -> fWith t
            | Not ops -> fNot (ops |> Array.map visit)
            | Or ops -> fOr (ops |> Array.map visit)

        visit op

/// Represents an instance of a trait used to initialize an entity; Tag traits are their own instances.
#if FABLE_COMPILER
[<TypeScriptTaggedUnion("type")>]
#endif
type TraitSpec =
    | Tag of ITagTrait
    | Val of (ITrait * obj) // Need to erase the types here for the sake of Spawn's signature.

    // It's static to make the name generated by Fable more palatable on the TypeScript side.
    static member Map fTag fValue config =
        match config with
        | Tag t -> fTag t
        | Val v -> fValue v

/// Represents an entity in the world that may have zero or more traits.
type IEntity =
    abstract Add: someTrait: ITrait -> unit
    abstract Destroy: unit -> unit
    abstract Get: valueTrait: IValueTrait<'T> -> 'T option
    abstract Has: someTrait: ITrait -> bool
    abstract Remove: someTrait: ITrait -> unit
    abstract Set: valueTrait: (IValueTrait<'T>) -> value: 'T -> unit
    abstract TargetFor: relation: IRelation<'TTrait> -> IEntity option
    abstract TargetsFor: relation: IRelation<'TTrait> -> IEntity seq

/// Represents a special trait that relates entitites.
and IRelation<'TTrait when 'TTrait :> ITrait> =
    /// Used to distinguish relations carrying ITagTrait from those carrying IValueTrait
    /// in TypeScript type tests. We could use a discriminated union of two interfaces
    /// instead, but doing it this way makes the F# types line up better.
    abstract IsTag: bool
    abstract On: entity: IEntity -> 'TTrait
    abstract Wildcard: unit -> 'TTrait

/// Represents the result of a query.
type IQueryResult<'T> =
    abstract Select: unit -> IQueryResult<unit>
    abstract UpdateEach: callback: ('T * IEntity -> unit) -> unit

/// Provides functionality to create new traits and relations.
type ITraitFactory =
    // Can't use overloadeed method names for tag vs. value relations because TS needs return types
    // of overloaded methods to be sub-types of each other. I don't want to use an erased union because
    // that seems less safe than a tagged union. This is the least bad compromise.
    abstract Relation: exclusive: bool -> IRelation<ITagTrait>
    abstract RelationWith: exclusive: bool * store: 'T -> IRelation<IValueTrait<'T>>
    // We're avoiding overloading here too to make things easier on the TypeScript side.
    abstract TagTrait: unit -> ITagTrait
    abstract TraitWith: value: 'T -> IValueTrait<'T>
    abstract TraitWithRef: valueFactory: (unit -> 'T) -> IValueTrait<'T>

module Extensions =
    type ITraitFactory with
        member this.Relation() = this.Relation(exclusive = false)

        member this.RelationWith(store: 'T) =
            this.RelationWith(exclusive = false, store = store)

/// Encapsulates all state of the world (traits indexed by entities) in one place
/// for centralized access.
type IWorld =
    abstract Get: valueTrait: IValueTrait<'T> -> 'T option
    abstract Has: someTrait: ITrait -> bool
    abstract Query: [<ParamArray>] where: QueryOperator[] -> IQueryResult<unit>
    abstract Query: traits: (IValueTrait<'T>) * [<ParamArray>] where: QueryOperator[] -> IQueryResult<'T>

    abstract Query:
        traits: (IValueTrait<'T> * IValueTrait<'U>) * [<ParamArray>] where: QueryOperator[] -> IQueryResult<'T * 'U>

    abstract QueryFirst: [<ParamArray>] where: QueryOperator[] -> IEntity option
    abstract Remove: someTrait: ITrait -> unit
    abstract Spawn: [<ParamArray>] traits: TraitSpec[] -> IEntity
