namespace Wilnaatahl.ECS

open System
open System.Collections.Generic
#if FABLE_COMPILER
open Fable.Core
#endif

// Here we define types that act as bindings to Koota, an ECS library for TypeScript.
// There interfaces can also be mocked in .NET tests to exercise the F# implementation
// of all our systems.
//
// While in theory these interfaces could map to any TypeScript ECS, their design is
// heavily biased towards Koota's for ease of interop.
//
// NOTE: The heavy use of interfaces is to facilitate interop with TypeScript.
// The Fable compiler won't mangle interface member names, and as much as I'd love
// to use discriminated unions here, they're pretty ugly in TypeScript.

/// Represents a trait (a.k.a. component or aspect) of a specific type
/// that can be added to or removed from an entity.
type ITrait =
    /// Used to distinguish ITagTrait from IValueTrait in TypeScript type tests.
    /// We can't use a discriminated union for traits because it would force the
    /// type parameter of IValueTrait up to this interface.
    abstract IsTag: bool

/// Represents a trait (a.k.a. component or aspect) that can be added to
/// or removed from an entity and represents a "tag" or "flag" on that entity.
type ITagTrait =
    inherit ITrait

/// Represents a trait (a.k.a. component or aspect) that can be added to
/// or removed from an entity and carries values of a specific type.
type IValueTrait<'T> =
    inherit ITrait

/// Represents a trait (a.k.a. component or aspect) that can be added to
/// or removed from an entity and carries mutable values of a specific type.
/// Separate types are used for the "read" and "write" operations purely
/// because F# lacks mutable anonymous records AND Koota requires POJOs in
/// order to create struct-of-array (SoA) traits, which are more efficient.
type IMutableValueTrait<'T, 'TMutable> =
    inherit IValueTrait<'T>

/// Represents a query criteria consisting of traits or combinations thereof.
#if FABLE_COMPILER
[<TypeScriptTaggedUnion("type")>]
#endif
type QueryOperator =
    | With of ITrait
    | Not of QueryOperator[]
    | Or of QueryOperator[]

    // It's static to make the name generated by Fable more palatable on the TypeScript side.
    static member Visit fWith fNot fOr op =
        let rec visit innerOp =
            match innerOp with
            | With t -> fWith t
            | Not ops -> fNot (ops |> Array.map visit)
            | Or ops -> fOr (ops |> Array.map visit)

        visit op

/// Represents an instance of a trait used to initialize an entity; Tag traits are their own instances.
type TraitSpec = // NOTE: We can't use TypeScriptTaggedUnion here as it breaks the generated TypeScript code for functions returning a TraitSpec.
    private // Private to force type-safe construction via TraitExtensions.
    | Tag of ITagTrait
    | Val of (ITrait * obj) // Need to erase the types here for the sake of Spawn's signature.

    // It's static to make the name generated by Fable more palatable on the TypeScript side.
    static member Map fTag fValue config =
        match config with
        | Tag t -> fTag t
        | Val v -> fValue v

/// Uniquely identifies an entity in the World; Entities may have zero or more traits.
#if FABLE_COMPILER
[<Erase>]
#endif
type EntityId = EntityId of int

/// Represent operations on entities in the World.
type IEntityOperations =
    abstract Add: someTrait: ITrait -> entity: EntityId -> unit
    abstract Destroy: entity: EntityId -> unit
    abstract Get: valueTrait: IValueTrait<'T> -> entity: EntityId -> 'T option
    abstract Has: someTrait: ITrait -> entity: EntityId -> bool
    abstract Remove: someTrait: ITrait -> entity: EntityId -> unit
    abstract Set: valueTrait: IValueTrait<'T> -> value: 'T -> entity: EntityId -> unit
    abstract SetWith: valueTrait: IValueTrait<'T> -> update: ('T -> 'T) -> entity: EntityId -> unit
    abstract TargetFor: relation: IRelation<'TTrait> -> entity: EntityId -> EntityId option
    abstract TargetsFor: relation: IRelation<'TTrait> -> entity: EntityId -> EntityId seq

/// Represents a special trait that relates entitites.
and IRelation<'TTrait when 'TTrait :> ITrait> =
    /// Used to distinguish relations carrying ITagTrait from those carrying IValueTrait
    /// in TypeScript type tests. We could use a discriminated union of two interfaces
    /// instead, but doing it this way makes the F# types line up better.
    abstract IsTag: bool
    abstract On: entity: EntityId -> 'TTrait
    abstract Wildcard: unit -> 'TTrait

/// Represents the result of a query.
type IQueryResult<'T, 'TMutable> =
    inherit IEnumerable<EntityId>
    abstract ForEach: callback: ('T * EntityId -> unit) -> unit
    abstract UpdateEach: callback: ('TMutable * EntityId -> unit) -> unit

/// Allows specifying options for the behaviour of relations.
type RelationConfig =
    { IsExclusive: bool }

    static member Default = { IsExclusive = false }

/// Provides functionality to create new traits and relations.
type ITraitFactory =
    // Can't use overloadeed method names for tag vs. value relations because TS needs return types
    // of overloaded methods to be sub-types of each other. I don't want to use an erased union because
    // that seems less safe than a tagged union. This is the least bad compromise.
    abstract Relation: config: RelationConfig -> IRelation<ITagTrait>

    abstract RelationWith:
        config: RelationConfig * store: 'T * mutableStore: 'TMutable -> IRelation<IMutableValueTrait<'T, 'TMutable>>
    // We're avoiding overloading here too to make things easier on the TypeScript side.
    abstract TagTrait: unit -> ITagTrait
    abstract TraitWith: value: 'T -> mutableValue: 'TMutable -> IMutableValueTrait<'T, 'TMutable>
    abstract TraitWithRef: valueFactory: (unit -> 'T) -> IMutableValueTrait<'T, 'T>

/// Encapsulates all state of the world (traits indexed by entities) in one place
/// for centralized access.
type IWorld =
    abstract Add: someTrait: ITrait -> unit
    abstract Get: valueTrait: IValueTrait<'T> -> 'T option
    abstract Has: someTrait: ITrait -> bool

    // It's less than ideal to not overload Query, but unfortunately it's next to impossible to correctly
    // implement overloaded methods on the TypeScript side when they involve variable argument lists, so
    // it's better to avoid it.
    abstract Query: [<ParamArray>] where: QueryOperator[] -> IQueryResult<unit, unit>

    abstract QueryTrait:
        someTrait: (IMutableValueTrait<'T, 'TMutable>) * [<ParamArray>] where: QueryOperator[] ->
            IQueryResult<'T, 'TMutable>

    abstract QueryTraits:
        firstTrait: IMutableValueTrait<'T, 'TMutable> *
        secondTrait: IMutableValueTrait<'U, 'UMutable> *
        [<ParamArray>] where: QueryOperator[] ->
            IQueryResult<'T * 'U, 'TMutable * 'UMutable>

    abstract QueryFirst: [<ParamArray>] where: QueryOperator[] -> EntityId option
    abstract Remove: someTrait: ITrait -> unit
    abstract Set: valueTrait: IValueTrait<'T> -> value: 'T -> unit
    abstract Spawn: [<ParamArray>] traits: TraitSpec[] -> EntityId

module TraitExtensions =
    type ITagTrait with
        member this.Tag() = Tag this

    type IValueTrait<'T> with
        member this.Val(value: 'T) = Val(this, value :> obj)
